{
  "formatVersion": "1.1",
  "component": {
    "group": "com.12id",
    "module": "holder-sdk-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "holder-sdk-android-0.2.0.aar",
          "url": "holder-sdk-android-0.2.0.aar",
          "size": 1873362,
          "sha512": "de4e1d9e485ff814dafbb3eefae2557383796deb8f2adbe6516e8c3456e116fc5e1b0f42b232a794b96464a2d93684448c71d3b76439be7d84b80487e145b992",
          "sha256": "74ea5ecb311c8cb7c0c6d09e179a4b887c55e5a41fded9fcc7dbac3ecb88a3e7",
          "sha1": "29bc66e243ceec47558e72e333478f6763e0da85",
          "md5": "2d6a949a9c5e0d9a57694f9267e94d68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.12id",
          "module": "holder-sdk-native",
          "version": {
            "requires": "0.2.1-12id.1"
          }
        },
        {
          "group": "org.didcommx",
          "module": "peerdid",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "com.github.multiformats",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "holder-sdk-android-0.2.0.aar",
          "url": "holder-sdk-android-0.2.0.aar",
          "size": 1873362,
          "sha512": "de4e1d9e485ff814dafbb3eefae2557383796deb8f2adbe6516e8c3456e116fc5e1b0f42b232a794b96464a2d93684448c71d3b76439be7d84b80487e145b992",
          "sha256": "74ea5ecb311c8cb7c0c6d09e179a4b887c55e5a41fded9fcc7dbac3ecb88a3e7",
          "sha1": "29bc66e243ceec47558e72e333478f6763e0da85",
          "md5": "2d6a949a9c5e0d9a57694f9267e94d68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "holder-sdk-android-0.2.0-sources.jar",
          "url": "holder-sdk-android-0.2.0-sources.jar",
          "size": 230898,
          "sha512": "89bea62f428a7d34b54056137118301262f37b7c928d5d3b91401aa0cf59c185c693128eaf1a27a00c2b9c954838fa822979d073506e5648a6cc2b7fd863e7a8",
          "sha256": "9c8fc82e88c11e2dc48e005613553d1c9057ad8ab4e26ac43aeec8d89222b300",
          "sha1": "6994f60eb846d1b5b438d22ad6f55040ff879209",
          "md5": "a0190c0a9c5f4b77abb74d7fc3bd4f03"
        }
      ]
    }
  ]
}
