{
  "formatVersion": "1.1",
  "component": {
    "group": "com.12id",
    "module": "holder-sdk-native",
    "version": "0.2.1-12id.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "holder-sdk-native-0.2.1-12id.1.aar",
          "url": "holder-sdk-native-0.2.1-12id.1.aar",
          "size": 24207788,
          "sha512": "a6046f56ac8094eb0125861a8753fc3ae9cc232738b67b7784f396733fe615032bde820b7a32f6e6138d99d450625f5520ae47b9607330f271bbe20817a09ba8",
          "sha256": "f47313e603059504179d55c59bfee330944e0f0103c57c1c25f1b52eb2623f05",
          "sha1": "0abcaf38dd8ddeafa65f267c9efd54b76223d224",
          "md5": "9a7a1b28a456e9d276b1eb548ecca0f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.22.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "holder-sdk-native-0.2.1-12id.1.aar",
          "url": "holder-sdk-native-0.2.1-12id.1.aar",
          "size": 24207788,
          "sha512": "a6046f56ac8094eb0125861a8753fc3ae9cc232738b67b7784f396733fe615032bde820b7a32f6e6138d99d450625f5520ae47b9607330f271bbe20817a09ba8",
          "sha256": "f47313e603059504179d55c59bfee330944e0f0103c57c1c25f1b52eb2623f05",
          "sha1": "0abcaf38dd8ddeafa65f267c9efd54b76223d224",
          "md5": "9a7a1b28a456e9d276b1eb548ecca0f3"
        }
      ]
    }
  ]
}
